name: Build
on:
  push:
    branches:
      - master
      - 'branch-*'
      - 'dogfood-*'
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write  # Vault OIDC
  contents: write  # Repository access

jobs:
  build:
    name: Build
    runs-on: github-ubuntu-latest-s
    timeout-minutes: 30
    steps:
      - &checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/build-maven@53ccf0ed05eb001e8b652deee1218b9baa9833f2 # v1 (1.2.1)
        with:
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          deploy-pull-request: true
      - name: Upload build reports on failure
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: build-reports
          path: '**/target/surefire-reports/**/*'
          if-no-files-found: ignore
      - name: Upload test results on failure
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: test-results
          path: '**/target/surefire-reports/**/*.xml'
          if-no-files-found: ignore

  promote:
    needs:
      - build
    runs-on: github-ubuntu-latest-s
    name: Promote
    steps:
      - *checkout
      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          cache_save: false
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/get-build-number@53ccf0ed05eb001e8b652deee1218b9baa9833f2 # v1 (1.2.1)
      - uses: SonarSource/ci-github-actions/promote@53ccf0ed05eb001e8b652deee1218b9baa9833f2 # v1 (1.2.1)
        with:
          promote-pull-request: true
